#!/usr/bin/env python3
"""Check every link on the site: they resolve, and anchors have targets.

`apply.py --check` proves a page's nav matches the spec. This proves the links
actually go somewhere — a link can be written consistently and still point at
nothing.

Two scopes, because they fail differently:

  * **nav links** are generated, so a mistake is systematic and appears on every
    page at once.
  * **body links** are hand-written or generated by a builder, and a mistake
    hides on one page. The workshops cards shipped with `../class-01/` — no
    `classes/` segment — and this script missed all twelve because it only read
    `<nav>` blocks.

Both are checked now, along with `src` attributes, so a missing image is caught
the same way.

    python3 tools/site-nav/verify-links.py
"""

from __future__ import annotations

import re
import sys
import urllib.parse
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent

NAV_BLOCK = re.compile(r'<nav class="(?:nav|site-nav|subnav)".*?</nav>', re.S)
SKIP_PARTS = {".git", "out", "brand", "node_modules"}
SKIP_SCHEMES = ("http://", "https://", "mailto:", "tel:", "data:", "javascript:")

# href and src, in either quote style. srcset is deliberately out: it only
# appears on the guide pages' screenshots, and the first candidate in a srcset
# is always present when the element renders.
LINK = re.compile(r'(?:href|src)\s*=\s*"([^"]*)"')

# Tags whose links are external by nature or not worth resolving.
IGNORE_PREFIX = ("//",)


def is_external(raw: str) -> bool:
    return raw.startswith(SKIP_SCHEMES) or raw.startswith(IGNORE_PREFIX) or raw.strip() == ""


def resolve(page: Path, raw: str):
    """(target_path or None, anchor or None) for a link on `page`.

    Returns (None, anchor) for a same-page fragment, and (path, anchor) when the
    link names a file. `#` alone yields (None, None) and is skipped by callers.
    """
    target_href, _, anchor = raw.partition("#")
    anchor = anchor or None

    if not target_href:
        return None, anchor  # a fragment on this page

    decoded = urllib.parse.unquote(target_href.split("?")[0])
    if decoded.startswith("/"):
        target = (ROOT / decoded.lstrip("/")).resolve()
    else:
        target = (page.parent / decoded).resolve()
    if decoded.endswith("/"):
        target = target / "index.html"
    return target, anchor


def check_page(path: Path, text: str):
    """Every link on one page. Returns (problems, counts, has_nav)."""
    rel = path.relative_to(ROOT)
    navs = NAV_BLOCK.findall(text)
    nav_links = set()
    for block in navs:
        nav_links.update(LINK.findall(block))

    problems = []
    counts = {"nav": 0, "body": 0, "anchors": 0}

    for raw in LINK.findall(text):
        if is_external(raw) or raw == "#":
            continue
        in_nav = raw in nav_links
        counts["nav" if in_nav else "body"] += 1
        where = "nav" if in_nav else "body"

        target, anchor = resolve(path, raw)

        if target is None:
            if anchor:
                counts["anchors"] += 1
                if f'id="{anchor}"' not in text:
                    problems.append(f"{rel} [{where}]: #{anchor} has no target on this page")
            continue

        if not target.exists():
            problems.append(f"{rel} [{where}]: {raw} -> no such file")
            continue
        if anchor:
            counts["anchors"] += 1
            if target.suffix == ".html" and f'id="{anchor}"' not in target.read_text(errors="replace"):
                problems.append(f"{rel} [{where}]: {raw} -> no #{anchor} in {target.name}")

    return problems, counts, bool(navs)


def main() -> int:
    problems = []
    totals = {"nav": 0, "body": 0, "anchors": 0}
    no_nav = []
    scanned = 0

    for path in sorted(ROOT.rglob("*.html")):
        if SKIP_PARTS & set(path.parts):
            continue
        scanned += 1
        text = path.read_text(errors="replace")
        found, counts, has_nav = check_page(path, text)
        problems += found
        for key in totals:
            totals[key] += counts[key]

        # A published page should have a nav. Slide decks and print handouts are
        # deliberately out: they are the printed artifact, and the in-browser
        # render outputs under out/ are skipped above.
        is_print_only = "slides.html" in path.name or path.parent.name == "handouts"
        if not has_nav and not is_print_only:
            no_nav.append(str(path.relative_to(ROOT)))

    print(f"{scanned} html files scanned")
    print(f"{totals['nav']} nav links, {totals['body']} body links, "
          f"{totals['anchors']} anchors checked")
    all_problems = problems + [f"{p}: no nav" for p in no_nav]
    if all_problems:
        print()
        for p in all_problems:
            print(f"  {p}")
        print(f"\n{len(all_problems)} problem(s).")
        return 1
    print("every link resolves and every anchor has a target.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
